"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from 'next/script';
import React from "react";
import { usePathname } from 'next/navigation';
import Head from 'next/head';
// import Scripts from "./scripts";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



export default function RootLayout({ children }) {
  const [isJQueryLoaded, setIsJQueryLoaded] = React.useState(false);
  console.log(isJQueryLoaded)
  return (
    <html lang="en">
      <head>
        <Head>
          <meta charSet="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <meta name="description" content="Generated by create next app" />
          <title>Create Next App</title>
        </Head>
        <link rel="stylesheet" type="text/css" href="/assets/css/animate.min.css" />
        <link rel="stylesheet" type="text/css" href="/assets/css/animation.css" />
        <link rel="stylesheet" type="text/css" href="/assets/css/nouislider.min.css" />
        <link rel="stylesheet" type="text/css" href="/assets/css/jquery.fancybox.min.css"></link>
        <link rel="stylesheet" type="text/css" href="/assets/css/nice-select.css" />
        <link rel="stylesheet" type="text/css" href="/assets/css/bootstrap.css" />
        <link
          rel="stylesheet"
          type="text/css"
          href="/assets/css/bootstrap-select.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="/assets/css/swiper-bundle.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="/assets/css/magnific-popup.min.css"
        />
        <link rel="stylesheet" type="text/css" href="/assets/css/mmenu.css" />
        <link rel="stylesheet" type="text/css" href="/assets/css/style.css" />

        {/* Fonts */}
        <link rel="stylesheet" href="/assets/font/fonts.css" />
        <link
          href="https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />

        {/* Icons */}
        <link rel="stylesheet" type="text/css" href="/assets/icon/flaticon_just-home.css" />
        <link rel="stylesheet" type="text/css" href="/assets/icon/icomoon/style.css" />

        {/* Favicon and Touch Icons */}
        <link rel="shortcut icon" href="/assets/images/favicon.png" />
        <link rel="apple-touch-icon-precomposed" href="/assets/images/favicon.png" />


      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}  body counter-scroll mm-wrapper`}>
        {children}
        <Script
          src="/assets/js/jquery.min.js"
          strategy="lazyOnload" // Load it after the page load
          onLoad={() => {
            if (window.jQuery) {
              console.log("jQuery loaded successfully.");
              setIsJQueryLoaded(true);
            }
          }}
          onError={(e) => console.error("Failed to load jQuery:", e)}
        />
        {isJQueryLoaded && (
          <>
            <Script src="/assets/js/bootstrap.min.js" strategy="afterInteractive" />

            <Script src="/assets/js/jquery.nice-select.min.js" strategy="afterInteractive" />
            <Script src="/assets/js/bootstrap-select.min.js" strategy="afterInteractive" />
            {/* <Script src="/assets/js/swiper-bundle.min.js" strategy="afterInteractive" /> */}
            {/* <Script src="/assets/js/swiper.js" strategy="afterInteractive" /> */}
            {/* <Script src="/assets/js/countto.js" strategy="afterInteractive" /> */}
            {/* <Script src="/assets/js/circletype.min.js" strategy="afterInteractive" /> */}
            <Script
              src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCFC3m2n0jBRFTMvUNZc0-6Y0Rzlcadzcw"
              async
              strategy="afterInteractive"
            />
            {/* <Script src="/assets/js/marker.js" strategy="afterInteractive" /> */}
            <Script src="/assets/js/jquery.fancybox.js" strategy="afterInteractive" />
            {/* <Script src="/assets/js/magnific-popup.min.js" strategy="afterInteractive" /> */}
            {/* <Script src="/assets/js/apexcharts.js" strategy="afterInteractive" /> */}
            {/* <Script src="/assets/js/area-chart.js" strategy="afterInteractive" /> */}
            {/* <Script src="/assets/js/morris.min.js" strategy="afterInteractive" /> */}
            {/* <Script src="/assets/js/raphael.min.js" strategy="afterInteractive" /> */}
            {/* <Script src="/assets/js/morris.js" strategy="afterInteractive" /> */}
            {/* <Script src="/assets/js/nouislider.min.js" strategy="afterInteractive" /> */}
            {/* <Script src="/assets/js/rangle-slider.js" strategy="afterInteractive" /> */}
            {/* <Script src="/assets/js/mmenu.js" strategy="afterInteractive" /> */}
            <Script src="/assets/js/wow.min.js" strategy="afterInteractive" />
            {/* <Script src="/assets/js/scrollmagic.js" strategy="afterInteractive" /> */}
            {/* <Script src="/assets/js/main.js" strategy="afterInteractive" /> */}
            {/* <Script src="/assets/js/maps.js" strategy="afterInteractive" /> */}
            {/* <Script src="/assets/js/infobox.min.js" strategy="afterInteractive" /> */}
            {/* <Scripts /> */}
          </>
        )}
      </body>
    </html>
  );
}
